//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int id { get; set; }
        public Nullable<int> idmarca { get; set; }
        public Nullable<int> idmodelo { get; set; }
        public string vin { get; set; }
        public Nullable<int> año { get; set; }
        public string Color { get; set; }
        public string placas { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public Nullable<bool> activo { get; set; }
        public string Estatus { get; set; }
        public Nullable<decimal> KilometrajeActual { get; set; }
        public string estadoFisico { get; set; }
        public string NotasFisicas { get; set; }
        public Nullable<int> NumeroEstacionamiento { get; set; }
        public string TipoEstacionamiento { get; set; }
        public string Propietario { get; set; }
    }
}
