//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheking
    {
        public int id { get; set; }
        public string Revicion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> idAuto { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> kilometrajeActual { get; set; }
        public Nullable<bool> valorint1 { get; set; }
        public Nullable<bool> valorint2 { get; set; }
        public Nullable<bool> valorint3 { get; set; }
        public Nullable<bool> valorint4 { get; set; }
        public Nullable<bool> valorint5 { get; set; }
        public Nullable<bool> valorint6 { get; set; }
        public Nullable<bool> valorint7 { get; set; }
        public Nullable<bool> valorint8 { get; set; }
        public Nullable<bool> valormot1 { get; set; }
        public Nullable<bool> valormot2 { get; set; }
        public Nullable<bool> valormot3 { get; set; }
        public Nullable<bool> valormot4 { get; set; }
        public Nullable<bool> valorpart1 { get; set; }
        public Nullable<bool> valorpart2 { get; set; }
        public Nullable<bool> valorpart3 { get; set; }
        public Nullable<bool> valorpart4 { get; set; }
        public Nullable<bool> valorex1 { get; set; }
        public Nullable<bool> valorex2 { get; set; }
        public Nullable<bool> valorex3 { get; set; }
        public Nullable<bool> valorex4 { get; set; }
        public Nullable<int> gasolina { get; set; }
        public Nullable<int> aceite { get; set; }
        public string imagenes { get; set; }
        public string notas { get; set; }
        public string FotoA { get; set; }
        public string FotoB { get; set; }
        public string FotoC { get; set; }
        public string FotoD { get; set; }
        public Nullable<bool> valordoc1 { get; set; }
        public Nullable<bool> valordoc2 { get; set; }
        public Nullable<bool> valordoc3 { get; set; }
        public Nullable<bool> valordoc4 { get; set; }
    }
}
