//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vtreact_Covume2Entities : DbContext
    {
        public vtreact_Covume2Entities()
            : base("name=vtreact_Covume2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Auto> Auto { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<auto_Fotos> auto_Fotos { get; set; }
        public virtual DbSet<Auto_Archivo> Auto_Archivo { get; set; }
        public virtual DbSet<Persona_Archivo> Persona_Archivo { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<serviciocategoria> serviciocategoria { get; set; }
        public virtual DbSet<ServicioTaller> ServicioTaller { get; set; }
        public virtual DbSet<tallerMecanico> tallerMecanico { get; set; }
        public virtual DbSet<Cheking> Cheking { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Siniestro> Siniestro { get; set; }
        public virtual DbSet<TipoSiniestro> TipoSiniestro { get; set; }
        public virtual DbSet<TipoSoporte> TipoSoporte { get; set; }
        public virtual DbSet<EntregaRecepcion_Vehiculo> EntregaRecepcion_Vehiculo { get; set; }
        public virtual DbSet<Entrega_Sevicios> Entrega_Sevicios { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<ServicioAuto> ServicioAuto { get; set; }
        public virtual DbSet<Grupo_Relacion_Servicio> Grupo_Relacion_Servicio { get; set; }
        public virtual DbSet<GrupoServicio> GrupoServicio { get; set; }
    }
}
