//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int Id { get; set; }
        public string Correo { get; set; }
        public string token { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombre { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Telefono { get; set; }
        public string Licencia { get; set; }
        public string Imagen { get; set; }
        public string estatus { get; set; }
        public Nullable<int> idAuto { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public Nullable<int> calificacion { get; set; }
        public Nullable<int> idPUesto { get; set; }
        public string Genero { get; set; }
        public string Referencia { get; set; }
        public string ReferenciaNumero { get; set; }
        public string Departamento { get; set; }
        public string TipoLicncia { get; set; }
        public string Extencion { get; set; }
        public string observacionCalificacion { get; set; }
    }
}
