//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_Archivo
    {
        public int id { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string archivo { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> activo { get; set; }
        public string estatus { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
    }
}
