//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioAuto
    {
        public int id { get; set; }
        public Nullable<int> idauto { get; set; }
        public Nullable<int> idservicio { get; set; }
        public Nullable<int> idorder { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fechaPservicio { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
