//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios
    {
        public int id { get; set; }
        public Nullable<int> idcategoria { get; set; }
        public Nullable<int> semanasGarantiaservicio { get; set; }
        public Nullable<int> diasRealizarServicio { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombreServicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> KilometrosProximoServicio { get; set; }
    }
}
