//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covem_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniestro
    {
        public int id { get; set; }
        public Nullable<int> idAuto { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> idTipoSiniestro { get; set; }
        public Nullable<int> IdTipoSoporte { get; set; }
        public string Estatus { get; set; }
        public string notas { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
